# imagino que en algun momento tendre que implementarlo

def errores():
    return